services:
  sunshine:
    build:
      context: .
      dockerfile: build/container/Dockerfile
    image: docker-arch-sunshine
    container_name: docker-arch-sunshine
    platform: linux/amd64
    stdin_open: true
    tty: true
    network_mode: host
    ipc: host
    privileged: true
    devices:
      - /dev/dri:/dev/dri
      - /dev/uinput:/dev/uinput
      - /dev/uhid:/dev/uhid
    device_cgroup_rules:
      - "c 13:* rmw"
      - "c 226:* rmw"
      - "c 244:* rmw"
    volumes:
      - ./mnt/user_data:/mnt/user_data
