sunshine_name = Docker Arch Sunshine
capture = x11
origin_web_ui_allowed = wan
lan_encryption_mode = 0
wan_encryption_mode = 0
upnp = disabled
stream_audio = enabled
audio_sink = arch_sunshine_audio.monitor
virtual_sink = arch_sunshine_audio
file_apps = /mnt/user_data/etc/sunshine/apps.json
file_state = /mnt/user_data/var/lib/sunshine/sunshine_state.json
credentials_file = /mnt/user_data/var/lib/sunshine/sunshine_state.json
log_path = /mnt/user_data/var/log/arch-sunshine/sunshine.log
