sunshine_name = Docker Arch Sunshine
capture = kwin
origin_web_ui_allowed = pc
lan_encryption_mode = 0
wan_encryption_mode = 0
upnp = disabled
system_tray = disabled
global_prep_cmd = [{"do":"/usr/local/bin/arch-sunshine client-start","undo":"/usr/local/bin/arch-sunshine client-stop"}]
stream_audio = enabled
audio_sink = arch_sunshine_audio
virtual_sink = arch_sunshine_audio
gamepad = xone
motion_as_ds4 = disabled
touchpad_as_ds4 = disabled
encoder = vaapi
file_apps = /run/arch-sunshine/sunshine/apps.json
file_state = /mnt/user_data/var/lib/sunshine/sunshine_state.json
credentials_file = /run/arch-sunshine/sunshine/credentials.json
log_path = /mnt/user_data/var/log/arch-sunshine/sunshine.log
